[package]
name = "wgpu-bencher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytemuck = "1.14.0"
log = "0.4.20"
tabled = "0.14.0"
wgpu = "0.18.0"
